# Site settings
title: Blog do DevInSanta
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  O DevInSanta é formado por desenvolvedores, empreendedores e entusiastas de tecnologia de Santarém - PA, aqui você pode aprender e ensinar, acreditamos  que compartilhando conhecimento, cresceremos juntos..
baseurl: "/blog" # the subpath of your site, e.g. /blog/
#twitter_username: jekyllrb
github_project:  "devinsanta/blog"
meetup_url: "http://meetup.com/devinsanta"
# Build settings
markdown: kramdown

gems:
  - jekyll-gist
